import {useEffect,useState} from "react";
import {Link} from "wouter";
import {Database,LockKeyhole,LogOut,Upload,ShieldCheck,History} from "lucide-react";

type Hist={id:string;filename:string;panelId:string;datasetType?:string;competence:string;rows:number;importedAt:string;user:string};
export default function Admin(){const [me,setMe]=useState<string|null>(null),[user,setUser]=useState("admin"),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[history,setHistory]=useState<Hist[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/admin/me');if(r.ok){const j=await r.json();setMe(j.user);const h=await fetch('/api/admin/history');if(h.ok)setHistory(await h.json())}};useEffect(()=>{load()},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMsg("");const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user,password})});const j=await r.json();setBusy(false);if(!r.ok)return setMsg(j.error||'Falha no login');setMe(j.user);setPassword('');load()};
 const logout=async()=>{await fetch('/api/admin/logout',{method:'POST'});setMe(null);setHistory([])};
 const upload=async(file:File,overwrite=false)=>{setBusy(true);setMsg('Lendo e validando o CSV...');const content=await file.text();const r=await fetch('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,content,overwrite})});const j=await r.json();if(r.status===409&&j.needsOverwrite){setBusy(false);if(confirm(`${j.error}\n\nDeseja substituir os dados existentes?`))return upload(file,true);setMsg('Importação cancelada.');return}setBusy(false);if(!r.ok)return setMsg(j.error||'Falha na importação');const periods=Array.isArray(j.summary.periods)?j.summary.periods.map((p:any)=>p.competence).join(', '):j.summary.competence;setMsg(`Importado: ${j.summary.datasetType || j.summary.panelId.toUpperCase()} • ${periods} • ${j.summary.rows} registros${j.summary.replaced?' • períodos existentes substituídos':''}.`);load()};
 return <div className="min-h-screen bg-[#03111f] text-slate-100"><header className="border-b border-sky-900/60 bg-[#041525]"><div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between"><Link href="/"><img src="/images/logos_institucionais.png" className="h-14 w-auto"/></Link><Link href="/" className="text-sm text-sky-400">← Área pública</Link></div></header><main className="max-w-6xl mx-auto px-5 py-10">
 {!me?<div className="max-w-md mx-auto rounded-2xl border border-sky-900 bg-[#071c30] p-7"><LockKeyhole className="w-9 h-9 text-sky-400 mb-4"/><h1 className="text-2xl font-bold">Administração</h1><p className="text-sm text-slate-400 mt-2">Acesso restrito para atualização dos dados do dashboard.</p><form onSubmit={login} className="mt-6 space-y-4"><label className="block text-sm">Usuário<input value={user} onChange={e=>setUser(e.target.value)} className="mt-2 w-full rounded-lg border border-sky-900 bg-[#03111f] px-4 py-3" autoComplete="username"/></label><label className="block text-sm">Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-sky-900 bg-[#03111f] px-4 py-3" autoComplete="current-password"/></label><button disabled={busy} className="w-full rounded-lg bg-sky-600 py-3 font-bold disabled:opacity-50">{busy?'Entrando...':'Entrar'}</button></form>{msg&&<p className="mt-4 text-sm text-amber-300">{msg}</p>}</div>:
 <><div className="flex flex-wrap justify-between gap-4 items-center mb-8"><div><p className="text-sky-400 text-xs tracking-[.25em] uppercase">Área restrita</p><h1 className="text-3xl font-bold mt-2">Gerenciador de dados</h1><p className="text-slate-400 mt-2">Usuário autenticado: {me}</p></div><button onClick={logout} className="flex items-center gap-2 rounded-lg border border-sky-900 px-4 py-2 text-sm"><LogOut className="w-4 h-4"/>Sair</button></div>
 <div className="grid lg:grid-cols-[1fr_.8fr] gap-6"><section className="rounded-2xl border border-sky-900 bg-[#071c30] p-6"><Upload className="w-9 h-9 text-sky-400"/><h2 className="text-xl font-bold mt-4">Importar nova competência</h2><p className="text-sm text-slate-400 mt-2">Envie o CSV original exportado do SIAPS. O sistema identifica automaticamente C1–C7, B1–B6, Territorial e os relatórios Quadrimestrais, além da competência/quadrimestre e equipes, antes de gravar.</p><label className="mt-6 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-sky-800 bg-[#041525] p-6 text-center hover:border-sky-500"><Database className="w-8 h-8 text-sky-400"/><span className="font-semibold mt-3">Selecionar arquivo CSV</span><span className="text-xs text-slate-500 mt-1">Máximo 12 MB</span><input type="file" accept=".csv,text/csv" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label>{msg&&<div className="mt-4 rounded-lg border border-sky-900 bg-[#03111f] p-4 text-sm">{msg}</div>}<div className="mt-5 flex gap-3 text-xs text-slate-400"><ShieldCheck className="w-5 h-5 shrink-0 text-emerald-400"/><p>O público não tem acesso à importação. Se a mesma competência já existir, o sistema exige confirmação antes de substituir.</p></div></section>
 <section className="rounded-2xl border border-sky-900 bg-[#071c30] p-6"><div className="flex items-center gap-2"><History className="w-5 h-5 text-sky-400"/><h2 className="text-xl font-bold">Histórico de importações</h2></div><div className="mt-5 space-y-3 max-h-[460px] overflow-auto">{history.length===0?<p className="text-sm text-slate-500">Nenhuma atualização administrativa registrada.</p>:history.map(h=><div key={h.id} className="rounded-lg border border-sky-900/70 bg-[#041525] p-3"><div className="flex justify-between gap-3"><b>{h.datasetType || h.panelId.toUpperCase()} • {h.competence}</b><span className="text-xs text-slate-500">{h.rows} registros</span></div><p className="text-xs text-slate-400 mt-1 break-all">{h.filename}</p><p className="text-xs text-slate-500 mt-1">{new Date(h.importedAt).toLocaleString('pt-BR')}</p></div>)}</div></section></div></>}
 </main></div>}
