import { useEffect, useMemo, useState } from "react";
import { useRoute } from "wouter";
import DataTable from "@/components/DataTable";
import RankingView from "@/components/RankingView";
import { allPanels } from "@/lib/mockData";
import { siapsData, SiapsPanelId } from "@/lib/siapsData";
import { BarChart3, ChevronDown, Download, Info, LayoutDashboard } from "lucide-react";

const monthOrder:Record<string,number>={JAN:1,FEV:2,MAR:3,ABR:4,MAI:5,JUN:6,JUL:7,AGO:8,SET:9,OUT:10,NOV:11,DEZ:12};
const sortComp=(a:string,b:string)=>{const [ma,ya]=a.split('/'),[mb,yb]=b.split('/'); return (+yb-+ya)||(monthOrder[mb]-monthOrder[ma]);};

export default function Dashboard(){
 const [,params]=useRoute("/:panelId"); const raw=(params?.panelId as string)||"infantil"; const panelId=(raw in siapsData?raw:"infantil") as SiapsPanelId;
 const panel=allPanels.find(p=>p.id===panelId)!; const [remote,setRemote]=useState<Record<string,any[]>>({}); useEffect(()=>{fetch(`/api/data/${panelId}`).then(r=>r.ok?r.json():{}).then(setRemote).catch(()=>setRemote({}))},[panelId]); const combined={...(siapsData[panelId] as any),...remote}; const comps=Object.keys(combined).sort(sortComp); const [competence,setCompetence]=useState(comps[0]); useEffect(()=>{if(comps.length&&!comps.includes(competence))setCompetence(comps[0])},[panelId,remote]); const [team,setTeam]=useState("all"); const [view,setView]=useState<"table"|"ranking">("table");
 const rows=(combined[competence]||[]) as readonly any[];
 const filtered=useMemo(()=>team==="all"?rows:rows.filter(r=>r.ine===team),[rows,team]);
 const vals=rows.map(r=>r.value).filter((v):v is number=>typeof v==="number"); const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;
 const classes=rows.reduce((a:any,r:any)=>{const k=r.classification||"Sem classificação";a[k]=(a[k]||0)+1;return a;},{});
 const practices=rows[0]?.practices?.map((p:any,idx:number)=>({label:p.label,avg:rows.reduce((s:any,r:any)=>s+(r.practices[idx]?.value||0),0)/Math.max(rows.length,1)}))||[];
 return <div className="min-h-screen bg-[#03111f] text-slate-100">
  <header className="bg-[#041525] border-b border-sky-900/60 sticky top-0 z-40 no-print"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-4"><a href="/"><img src="/images/logos_institucionais.png" className="h-14 sm:h-16 w-auto object-contain" alt="Logos institucionais"/></a><a href="/" className="text-sm text-sky-400 hover:text-sky-300">← Tela inicial</a></div></header>
  <main className="max-w-7xl mx-auto px-4 sm:px-6 py-7">
   <section className="flex flex-col lg:flex-row lg:items-end justify-between gap-5 mb-7"><div><div className="flex items-center gap-2 text-sm font-semibold text-blue-700 mb-2"><LayoutDashboard className="w-4 h-4"/> {panel.code} • Indicadores São Sebastião - SP</div><h2 className="text-2xl sm:text-3xl font-bold">{panel.description}</h2><p className="text-slate-400 mt-2">Dados preliminares importados dos relatórios SIAPS fornecidos pelo município.</p></div><button onClick={()=>window.print()} className="no-print flex items-center gap-2 px-4 py-2.5 bg-slate-900 text-white rounded-lg"><Download className="w-4 h-4"/> Imprimir / Salvar PDF</button></section>
   <section className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-7"><Card label="Competência" value={competence}/><Card label="Equipes" value={String(rows.length)}/><Card label="Média das equipes" value={`${avg.toFixed(2)}%`}/><Card label="Classificações" value={Object.keys(classes).length.toString()}/></section>
   <section className="no-print bg-[#071c30] p-5 rounded-xl border border-sky-900/70 shadow-sm mb-7"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-[1fr_1fr_auto] gap-4 items-end"><Select label="Competência" value={competence} onChange={(v)=>{setCompetence(v);setTeam('all')}} options={comps.map(c=>[c,c])}/><Select label="Equipe" value={team} onChange={setTeam} options={[["all","Todas as equipes"],...rows.map((r:any)=>[r.ine,r.name])]}/><div className="flex gap-2"><button onClick={()=>setView('table')} className={`px-4 py-2.5 rounded-lg font-semibold ${view==='table'?'bg-blue-700 text-white':'bg-gray-100'}`}>Equipes</button><button onClick={()=>setView('ranking')} className={`px-4 py-2.5 rounded-lg font-semibold ${view==='ranking'?'bg-blue-700 text-white':'bg-gray-100'}`}>Ranking</button></div></div></section>
   <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-7">{Object.entries(classes).map(([k,v])=><div key={k} className="bg-[#071c30] rounded-xl border border-sky-900/70 p-4"><p className="text-xs uppercase text-slate-400 font-semibold">{k}</p><p className="text-2xl font-bold mt-1">{String(v)}</p></div>)}</section>
   {practices.length>0&&<section className="mb-7"><div className="flex items-center gap-2 mb-3"><BarChart3 className="w-5 h-5 text-blue-700"/><h3 className="font-bold text-lg">Boas práticas registradas</h3></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{practices.map((p:any,i:number)=><div key={i} className="bg-[#071c30] border border-sky-900/70 rounded-xl p-4"><p className="text-sm font-medium text-slate-200">{p.label}</p><p className="text-xs text-slate-400 mt-2">Média de registros por equipe: <b>{p.avg.toFixed(1)}</b></p></div>)}</div></section>}
   <section><h3 className="text-lg font-bold mb-4">{view==='table'?'Resultados por equipe':'Ranking por resultado'}</h3>{view==='table'?<DataTable rows={filtered}/>:<RankingView rows={filtered}/>}</section>
   <div className="mt-7 flex gap-2 text-xs text-slate-400 no-print"><Info className="w-4 h-4 shrink-0"/><p>Fonte: arquivos CSV exportados do SIAPS. Os arquivos recebidos estão identificados como “Dado Preliminar”. A média municipal exibida nesta versão é a média simples dos resultados das equipes na competência selecionada.</p></div>
  </main></div>
}
function Card({label,value}:{label:string,value:string}){return <div className="bg-[#071c30] p-5 rounded-xl border border-sky-900/70 shadow-sm"><p className="text-xs uppercase tracking-wide font-semibold text-slate-400">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
function Select({label,value,onChange,options}:{label:string,value:string,onChange:(v:string)=>void,options:string[][]}){return <div><label className="block text-sm font-semibold mb-2">{label}</label><div className="relative"><select value={value} onChange={e=>onChange(e.target.value)} className="w-full px-4 py-2.5 pr-10 border rounded-lg bg-[#071c30]">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none"/></div></div>}
