import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, BarChart3, FileBarChart, Heart, Home, Info, MapPinned, Moon, Stethoscope, ChevronRight, Baby, PersonStanding, Ribbon, Droplets, Smile, ExternalLink } from "lucide-react";

const aps = [
  ["C1", "Mais Acesso à APS", "Acesso e utilização dos serviços", "/acesso", "acesso", "text-sky-400", "border-sky-500/30", "APS"],
  ["C2", "Desenvolvimento Infantil", "Acompanhamento de crianças menores de 2 anos", "/infantil", "infantil", "text-emerald-400", "border-emerald-500/30", "APS"],
  ["C3", "Gestação e Puerpério", "Acompanhamento pré-natal e puerpério", "/gestante", "gestante", "text-rose-400", "border-rose-500/30", "APS"],
  ["C4", "Pessoa com Diabetes", "Acompanhamento das pessoas com diabetes", "/diabetes", "diabetes", "text-amber-400", "border-amber-500/30", "APS"],
  ["C5", "Pessoa com Hipertensão", "Acompanhamento das pessoas com hipertensão", "/hipertensao", "hipertensao", "text-violet-400", "border-violet-500/30", "APS"],
  ["C6", "Pessoa Idosa", "Acompanhamento da população idosa", "/idosa", "idosa", "text-cyan-400", "border-cyan-500/30", "APS"],
  ["C7", "Prevenção do Câncer", "Cuidado da mulher na prevenção do câncer", "/cancer", "cancer", "text-orange-400", "border-orange-400/30", "APS"],
] as const;
const oral = [
  ["B1", "Primeira Consulta Odontológica Programada", "/dados/b1", "b1"], ["B2", "Tratamento Concluído", "/dados/b2", "b2"], ["B3", "Taxa de Exodontias", "/dados/b3", "b3"], ["B4", "Escovação Supervisionada", "/dados/b4", "b4"], ["B5", "Procedimentos Odontológicos Preventivos", "/dados/b5", "b5"], ["B6", "Tratamento Restaurador Atraumático (TRA)", "/dados/b6", "b6"],
] as const;
const apsLabels: Record<string, string> = Object.fromEntries(aps.map(([code, title, , , id]) => [id, `${code} — ${title}`]));
const oralLabels: Record<string, string> = Object.fromEntries(oral.map(([code, title, , id]) => [id, `${code} — ${title}`]));

type Highlight = { position: number; name: string; ine: string; value: number; classification: string };
type PanelHighlight = { panelId: string; competence: string; totalRows: number; valueRows: number; rows: Highlight[] };
type QuadrimestralOralHighlight = PanelHighlight & { available: boolean };
type Summary = { monthly: { competence: string; label: string; aps: Record<string, PanelHighlight>; oral: Record<string, PanelHighlight> } | null; quadrimestral: { competence: string | null; aps: PanelHighlight; oral: QuadrimestralOralHighlight } };

export default function Landing() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [apsPanel, setApsPanel] = useState("acesso");
  const [oralPanel, setOralPanel] = useState("b1");
  useEffect(() => { fetch("/api/public/summary").then(response => response.ok ? response.json() : null).then(setSummary).catch(() => setSummary(null)); }, []);
  const monthly = summary?.monthly || null;
  const apsHighlight = monthly?.aps[apsPanel];
  const oralHighlight = monthly?.oral[oralPanel];
  const monthlyLabel = monthly?.label || "Dados ainda não disponíveis";
  const quadrimestre = summary?.quadrimestral;

  return <div className="min-h-screen bg-[#03111f] text-slate-100">
    <header className="border-b border-sky-900/60 bg-[#041525]/95 sticky top-0 z-40"><div className="max-w-[1500px] mx-auto px-5 lg:px-8 h-24 flex items-center justify-between gap-6"><img src="/images/logos_institucionais.png" className="h-16 lg:h-20 w-auto object-contain" alt="SESAU, Fundação e Prefeitura de São Sebastião"/><div className="hidden md:flex items-center gap-8 text-sm text-slate-300"><span className="text-sky-400 flex items-center gap-2"><Home className="w-4 h-4"/>Início</span><span>Sobre</span><span>Metodologia</span><span>Documentos</span><span>Contato</span></div><div className="hidden xl:flex items-center gap-3 text-sm text-slate-300"><Moon className="w-4 h-4 text-sky-400"/> Modo Escuro</div></div></header>
    <main className="max-w-[1500px] mx-auto px-5 lg:px-8 py-9">
      <section className="grid xl:grid-cols-[1fr_360px] gap-7 items-start mb-8"><div><p className="text-sky-400 tracking-[.3em] uppercase text-xs font-bold mb-3">Bem-vindo ao</p><h1 className="text-3xl md:text-5xl font-black tracking-tight">Dashboard de Indicadores de Saúde</h1><p className="text-xl md:text-2xl text-sky-200 mt-2">São Sebastião – SP</p><p className="max-w-3xl text-slate-400 mt-5 leading-relaxed">Acompanhe os resultados das equipes de Saúde da Família e dos indicadores de saúde do município, com base nos dados do SIAPS/e-SUS APS.</p></div><div className="rounded-2xl border border-sky-800/70 bg-[#071c30] p-5"><div className="flex gap-4 items-center"><BarChart3 className="w-9 h-9 text-sky-400"/><div><p className="text-xs text-sky-300">Dados de referência</p><p className="font-bold text-lg">{monthlyLabel}</p></div></div><div className="border-t border-sky-900 mt-4 pt-4 text-xs text-slate-400 flex gap-2"><Info className="w-4 h-4 shrink-0 text-sky-400"/>Dados provenientes dos relatórios persistidos do SIAPS/e-SUS APS. Dado preliminar.</div></div></section>
      <HighlightsSection monthly={monthly} apsPanel={apsPanel} setApsPanel={setApsPanel} oralPanel={oralPanel} setOralPanel={setOralPanel} apsHighlight={apsHighlight} oralHighlight={oralHighlight} quadrimestre={quadrimestre} />
      <h2 className="text-2xl font-bold mb-5">Indicadores e Componentes</h2>
      <section className="rounded-2xl border border-sky-800/70 bg-[#061829] p-4 md:p-6 mb-6"><div className="flex items-center gap-4 mb-5"><div className="rounded-full border border-sky-500 p-3"><Stethoscope className="w-6 h-6 text-sky-400"/></div><div><h3 className="text-xl font-bold">Atenção Básica</h3><p className="text-slate-400 text-sm">Indicadores de desempenho da APS – C1 a C7</p></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 gap-3">{aps.map(([code,title,desc,href,,color,border])=><Link href={href} key={code} className={`group min-h-56 rounded-xl border ${border} bg-[#081a2c] p-4 hover:-translate-y-1 hover:bg-[#0a2138] transition`}><div className="flex justify-between items-center"><b className={`text-3xl ${color}`}>{code}</b><Activity className={`w-7 h-7 ${color}`}/></div><h4 className="font-bold mt-5 leading-tight">{title}</h4><p className="text-xs text-slate-400 mt-3 leading-relaxed">{desc}</p><span className="mt-5 inline-flex items-center gap-1 text-xs text-sky-400">Ver resultados <ChevronRight className="w-3 h-3"/></span></Link>)}</div></section>
      <section className="grid xl:grid-cols-[1.5fr_.8fr_.7fr] gap-5"><div className="rounded-2xl border border-cyan-800/70 bg-[#061829] p-5"><div className="flex items-center gap-3 mb-5"><Smile className="w-7 h-7 text-cyan-400"/><div><h3 className="text-xl font-bold">Saúde Bucal</h3><p className="text-sm text-slate-400">Indicadores de Saúde Bucal – B1 a B6</p></div></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 xl:grid-cols-3 gap-3">{oral.map(([code,title,href])=><Link href={href} key={code} className="rounded-xl border border-cyan-900 bg-[#081a2c] p-3 min-h-32 hover:bg-[#0a2138] transition"><b className="text-cyan-400 text-xl">{code}</b><p className="font-semibold text-sm mt-3 leading-tight">{title}</p><span className="text-xs text-sky-400 mt-3 inline-block">Ver resultados →</span></Link>)}</div></div>
       <Link href="/dados/territorial" className="rounded-2xl border border-violet-800/70 bg-[#07192b] p-6 flex flex-col hover:bg-[#0a2138] transition"><MapPinned className="w-10 h-10 text-violet-400 mb-5"/><h3 className="text-xl font-bold">Vínculo e Acompanhamento Territorial</h3><p className="text-sm text-slate-400 mt-3">Indicadores de vínculo, cadastro e acompanhamento das populações adscritas.</p><span className="mt-auto pt-8 text-sky-400 text-sm">Acessar →</span></Link>
       <Link href="/dados/quadrimestral-qualidade" className="rounded-2xl border border-orange-800/70 bg-[#07192b] p-6 flex flex-col hover:bg-[#0a2138] transition"><FileBarChart className="w-10 h-10 text-orange-400 mb-5"/><h3 className="text-xl font-bold">Relatório Quadrimestral</h3><p className="text-sm text-slate-400 mt-3">Visão consolidada dos indicadores da APS e panorama das competências.</p><span className="mt-auto pt-8 text-sky-400 text-sm">Acessar →</span></Link>
      </section>
    </main><footer className="border-t border-sky-900/70 mt-8"><div className="max-w-[1500px] mx-auto px-5 lg:px-8 py-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span>Município de São Sebastião – SP</span><span>Secretaria Municipal de Saúde</span><span>Fonte: SIAPS / e-SUS APS</span><span className="ml-auto">Transparência • Inovação • Eficiência</span><Link href="/admin" className="text-slate-600 hover:text-sky-400">Administração</Link></div></footer>
  </div>;
}

function HighlightsSection({ monthly, apsPanel, setApsPanel, oralPanel, setOralPanel, apsHighlight, oralHighlight, quadrimestre }: { monthly: Summary["monthly"]; apsPanel: string; setApsPanel: (value: string) => void; oralPanel: string; setOralPanel: (value: string) => void; apsHighlight?: PanelHighlight; oralHighlight?: PanelHighlight; quadrimestre?: Summary["quadrimestral"] }) {
  return <section className="mb-8"><div className="flex items-end justify-between gap-4 mb-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-400 font-bold">Resumo executivo</p><h2 className="text-2xl font-bold mt-1">Destaques das Equipes</h2></div><p className="text-xs text-slate-400 text-right max-w-sm">Resultados oficiais por indicador, sem combinação entre C1–C7 ou B1–B6.</p></div><div className="grid xl:grid-cols-2 gap-5">
    <HighlightCard title={`Destaques APS — ${monthly?.competence || "sem competência"}`} options={Object.keys(apsLabels)} value={apsPanel} onChange={setApsPanel} labels={apsLabels} highlight={apsHighlight} href={`/${apsPanel}`} emptyText="Nenhum resultado APS disponível nesta competência." />
    <HighlightCard title={`Destaques Saúde Bucal — ${monthly?.competence || "sem competência"}`} options={Object.keys(oralLabels)} value={oralPanel} onChange={setOralPanel} labels={oralLabels} highlight={oralHighlight} href={`/dados/${oralPanel}`} emptyText="Nenhum resultado de Saúde Bucal disponível nesta competência." />
    <HighlightCard title={`Destaques APS — ${quadrimestre?.competence || "sem quadrimestre"}`} highlight={quadrimestre?.aps} href="/dados/quadrimestral-qualidade" quadrimestre emptyText="Nenhum resultado quadrimestral oficial disponível." />
    <HighlightCard title={`Destaques Saúde Bucal — ${quadrimestre?.competence || "sem quadrimestre"}`} highlight={quadrimestre?.oral.available ? quadrimestre.oral : undefined} href="/dados/quadrimestral-qualidade" quadrimestre emptyText="Nenhum resultado quadrimestral oficial de Saúde Bucal disponível." />
  </div></section>;
}

function HighlightCard({ title, options, value, onChange, labels, highlight, href, quadrimestre = false, emptyText }: { title: string; options?: string[]; value?: string; onChange?: (value: string) => void; labels?: Record<string, string>; highlight?: PanelHighlight; href: string; quadrimestre?: boolean; emptyText: string }) {
  const shown = highlight?.rows || [];
  return <div className="rounded-2xl border border-sky-800/70 bg-[#061829] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-sky-300">{quadrimestre ? "Nota Final oficial" : "Resultado oficial"}</p><h3 className="font-bold text-lg text-white">{title}</h3></div>{options && <select aria-label="Selecionar indicador" value={value} onChange={event => onChange?.(event.target.value)} className="rounded-lg border border-sky-700 bg-[#03111f] px-3 py-2 text-sm text-slate-100">{options.map(option => <option key={option} value={option}>{labels?.[option] || option}</option>)}</select>}</div>{highlight && <p className="mt-3 text-xs text-slate-400">{highlight.valueRows} de {highlight.totalRows} equipes com resultado</p>}<div className="mt-4 space-y-2">{shown.map(row => <div key={`${row.ine}-${row.position}`} className="flex items-center gap-3 rounded-xl border border-sky-900/70 bg-[#081d31] px-3 py-2.5"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-sky-500/15 text-sm font-bold text-sky-100">{row.position}º</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{row.name}</p><p className="text-xs text-slate-400">{row.classification || "Classificação não informada"}</p></div><b className="text-sm text-white">{row.value.toFixed(2)}</b></div>)}{!shown.length && <p className="rounded-xl border border-sky-900/70 bg-[#051426] p-4 text-sm text-slate-400">{emptyText}</p>}</div><Link href={href} className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-sky-300 hover:text-white">Ver análise completa <ExternalLink className="h-3 w-3"/></Link></div>;
}
