import {useEffect,useMemo,useState} from "react";
import {Link,useLocation} from "wouter";
import {Download,FileBarChart,Info,MapPinned,Search,Tooth} from "lucide-react";

type Metric={label:string;value:number|null;text?:string};
type Row={ine:string;cnes:string;establishment:string;name:string;teamType:string;value:number|null;classification:string;practices?:{label:string;value:number|null}[];metrics?:Metric[];dimension?:string;indicator?:string;finalValue?:number|null;finalClassification?:string};
const defs:Record<string,{title:string;subtitle:string;kind:"oral"|"territorial"|"quadrimestral";icon:any}>={
 b1:{title:"B1 • Primeira Consulta Odontológica Programada",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 b2:{title:"B2 • Tratamento Odontológico Concluído",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 b3:{title:"B3 • Taxa de Exodontias",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 b4:{title:"B4 • Escovação Supervisionada",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 b5:{title:"B5 • Procedimentos Odontológicos Individuais Preventivos",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 b6:{title:"B6 • Tratamento Restaurador Atraumático (TRA)",subtitle:"Saúde Bucal",kind:"oral",icon:Tooth},
 territorial:{title:"Vínculo e Acompanhamento Territorial",subtitle:"Visão geral por equipe",kind:"territorial",icon:MapPinned},
 "territorial-detalhe":{title:"Vínculo e Acompanhamento Territorial",subtitle:"Detalhamento do componente",kind:"territorial",icon:MapPinned},
 "quadrimestral-qualidade":{title:"Desempenho Quadrimestral • Qualidade",subtitle:"Resultado consolidado por equipe",kind:"quadrimestral",icon:FileBarChart},
 "quadrimestral-cvat":{title:"Desempenho Quadrimestral • Vínculo e Acompanhamento Territorial",subtitle:"Cadastro, acompanhamento e nota final",kind:"quadrimestral",icon:FileBarChart},
};
const months:Record<string,number>={JAN:1,FEV:2,MAR:3,ABR:4,MAI:5,JUN:6,JUL:7,AGO:8,SET:9,OUT:10,NOV:11,DEZ:12};
function periodSort(a:string,b:string){if(/^Q/.test(a)&&/^Q/.test(b)){const [qa,ya]=a.slice(1).split('/').map(Number),[qb,yb]=b.slice(1).split('/').map(Number);return yb-ya||qb-qa}const [ma,ya]=a.split('/'),[mb,yb]=b.split('/');return (+yb-+ya)||(months[mb]||0)-(months[ma]||0)}
const fmt=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(v);
export default function PublicDataset(){
 const [location]=useLocation();const id=location.split("/").filter(Boolean).pop()||"b1",def=defs[id];const [data,setData]=useState<Record<string,Row[]>>({}),[period,setPeriod]=useState(""),[query,setQuery]=useState(""),[team,setTeam]=useState("all");
 useEffect(()=>{if(!def)return;fetch(`/api/data/${id}`).then(r=>r.ok?r.json():{}).then(j=>setData(j||{})).catch(()=>setData({}))},[id]);
 const periods=useMemo(()=>Object.keys(data).sort(periodSort),[data]);useEffect(()=>{if(periods.length&&!periods.includes(period))setPeriod(periods[0])},[periods,id]);
 const rows=data[period]||[];const teams=useMemo(()=>Array.from(new Map(rows.map(r=>[r.ine,r])).values()).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")),[rows]);
 const filtered=rows.filter(r=>(team==="all"||r.ine===team)&&(!query||`${r.name} ${r.establishment} ${r.ine} ${r.cnes} ${r.dimension||""} ${r.indicator||""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))));
 const uniqueTeams=new Set(rows.map(r=>r.ine)).size;const finals=Array.from(new Map(rows.filter(r=>r.finalValue!=null).map(r=>[r.ine,r.finalValue as number])).values());const vals=finals.length?finals:rows.map(r=>r.value).filter((v):v is number=>typeof v==="number");const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;
 if(!def)return <div className="min-h-screen bg-[#03111f] text-white p-10"><Link href="/">← Tela inicial</Link></div>;
 const Icon=def.icon;
 return <div className="min-h-screen bg-[#03111f] text-slate-100"><header className="border-b border-sky-900/60 bg-[#041525] sticky top-0 z-40 no-print"><div className="max-w-7xl mx-auto px-5 py-3 flex items-center justify-between"><Link href="/"><img src="/images/logos_institucionais.png" className="h-14 sm:h-16 w-auto object-contain" alt="Logos institucionais"/></Link><Link href="/" className="text-sm text-sky-400">← Tela inicial</Link></div></header>
 <main className="max-w-7xl mx-auto px-5 py-8"><section className="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><p className="text-sky-400 text-xs font-bold tracking-[.25em] uppercase">{def.subtitle}</p><div className="flex gap-3 items-center mt-2"><Icon className="w-8 h-8 text-cyan-400"/><h1 className="text-2xl md:text-3xl font-black">{def.title}</h1></div><p className="text-slate-400 mt-3">Consulta pública dos dados importados do SIAPS/e-SUS APS.</p></div><button onClick={()=>window.print()} className="no-print rounded-lg bg-sky-600 px-4 py-2.5 flex items-center gap-2"><Download className="w-4 h-4"/>Imprimir / Salvar PDF</button></section>
 <nav className="no-print mt-6 flex flex-wrap gap-2">{def.kind==="oral"&&["b1","b2","b3","b4","b5","b6"].map(x=><Link key={x} href={`/dados/${x}`} className={`rounded-lg border px-3 py-2 text-sm ${id===x?"border-cyan-500 bg-cyan-950/50 text-cyan-300":"border-sky-900 text-slate-400"}`}>{x.toUpperCase()}</Link>)}{def.kind==="territorial"&&<><Link href="/dados/territorial" className={`rounded-lg border px-3 py-2 text-sm ${id==="territorial"?"border-violet-500 text-violet-300":"border-sky-900 text-slate-400"}`}>Visão geral</Link><Link href="/dados/territorial-detalhe" className={`rounded-lg border px-3 py-2 text-sm ${id==="territorial-detalhe"?"border-violet-500 text-violet-300":"border-sky-900 text-slate-400"}`}>Detalhado</Link></>}{def.kind==="quadrimestral"&&<><Link href="/dados/quadrimestral-qualidade" className={`rounded-lg border px-3 py-2 text-sm ${id==="quadrimestral-qualidade"?"border-orange-500 text-orange-300":"border-sky-900 text-slate-400"}`}>Componente Qualidade</Link><Link href="/dados/quadrimestral-cvat" className={`rounded-lg border px-3 py-2 text-sm ${id==="quadrimestral-cvat"?"border-orange-500 text-orange-300":"border-sky-900 text-slate-400"}`}>Vínculo e Territorial</Link></>}</nav>
 {periods.length===0?<section className="mt-8 rounded-2xl border border-sky-900 bg-[#071c30] p-8"><Info className="w-8 h-8 text-sky-400"/><h2 className="font-bold text-xl mt-4">Nenhum dado publicado neste módulo</h2><p className="text-slate-400 mt-2">A estrutura pública está pronta. Quando um administrador importar o CSV correspondente, as competências ou quadrimestres aparecerão aqui automaticamente.</p></section>:<>
 <section className="grid sm:grid-cols-3 gap-4 mt-8"><Card label={def.kind==="quadrimestral"?"Quadrimestre":"Competência"} value={period}/><Card label="Equipes" value={String(uniqueTeams)}/><Card label={def.kind==="quadrimestral"?"Média das notas finais":"Média dos resultados"} value={fmt(avg)}/></section>
 <section className="no-print mt-5 rounded-xl border border-sky-900 bg-[#071c30] p-4 grid md:grid-cols-3 gap-3"><label className="text-xs text-slate-400">Período<select value={period} onChange={e=>{setPeriod(e.target.value);setTeam("all")}} className="mt-1 w-full rounded-lg border border-sky-900 bg-[#03111f] px-3 py-2.5 text-slate-100">{periods.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-xs text-slate-400">Equipe<select value={team} onChange={e=>setTeam(e.target.value)} className="mt-1 w-full rounded-lg border border-sky-900 bg-[#03111f] px-3 py-2.5 text-slate-100"><option value="all">Todas as equipes</option>{teams.map(t=><option value={t.ine} key={t.ine}>{t.name}</option>)}</select></label><label className="text-xs text-slate-400">Pesquisar<div className="relative mt-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Equipe, INE, indicador..." className="w-full rounded-lg border border-sky-900 bg-[#03111f] pl-9 pr-3 py-2.5 text-slate-100"/></div></label></section>
 <section className="mt-5 rounded-2xl border border-sky-900 bg-[#071c30] overflow-hidden"><div className="p-5 border-b border-sky-900"><h2 className="font-bold text-lg">Resultados por equipe</h2><p className="text-xs text-slate-500 mt-1">{filtered.length} registro(s) exibido(s). INE e CNES preservados do arquivo de origem.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#041525] text-slate-400"><tr><th className="text-left p-3">Equipe</th><th className="text-left p-3">INE</th>{def.kind==="quadrimestral"&&<><th className="text-left p-3">Dimensão / Indicador</th></>}<th className="text-right p-3">Resultado</th>{def.kind==="quadrimestral"&&<th className="text-right p-3">Nota final</th>}<th className="text-left p-3">Classificação</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={`${r.ine}-${r.dimension}-${r.indicator}-${i}`} className="border-t border-sky-900/60 align-top"><td className="p-3"><b>{r.name}</b><div className="text-xs text-slate-500">{r.establishment} • CNES {r.cnes}</div>{r.metrics?.length?<div className="mt-2 flex flex-wrap gap-1.5">{r.metrics.map((m,j)=><span key={j} className="rounded bg-[#0b2943] px-2 py-1 text-xs text-slate-300">{m.label}: {m.text||fmt(m.value)}</span>)}</div>:null}</td><td className="p-3 font-mono text-xs text-slate-400">{r.ine}</td>{def.kind==="quadrimestral"&&<td className="p-3"><div>{r.dimension||"—"}</div>{r.indicator&&<div className="text-xs text-slate-500 mt-1">{r.indicator}</div>}</td>}<td className="p-3 text-right font-bold text-cyan-300">{fmt(r.value)}</td>{def.kind==="quadrimestral"&&<td className="p-3 text-right font-bold">{fmt(r.finalValue)}</td>}<td className="p-3"><Badge text={r.finalClassification||r.classification}/></td></tr>)}</tbody></table></div></section>
 </>}
 <p className="mt-5 text-xs text-slate-500 flex gap-2"><Info className="w-4 h-4 shrink-0"/>Fonte: arquivos SIAPS/e-SUS APS importados pela área administrativa. Os valores são apresentados conforme o arquivo de origem; não há recálculo silencioso no navegador.</p></main></div>;
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-sky-900 bg-[#071c30] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="text-2xl font-black mt-2">{value}</p></div>}
function Badge({text}:{text:string}){if(!text)return <span className="text-slate-500">—</span>;return <span className="inline-flex rounded-full border border-sky-800 bg-[#0b2943] px-2.5 py-1 text-xs font-semibold">{text}</span>}
